apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spin-installer
  labels:
    app: spin-installer
spec:
  selector:
    matchLabels:
      app: spin-installer
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: spin-installer
        app: spin-installer
    spec:
      hostPID: true
      volumes:
        - name: node-root
          hostPath:
            path: /
      initContainers:
        - image: 0xe282b0/spin-openshift-installer
          name: spin-installer
          env:
            - name: NODE_ROOT
              value: /mnt/node-root
          securityContext:
            privileged: true
          volumeMounts:
            - name: node-root
              mountPath: /mnt/node-root/
      containers:
        - image: k8s.gcr.io/pause:3.1
          name: pause